---

services:
  postgres:
    image: postgres:14
    container_name: softuni-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - my-postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - softuni

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - my-data:/var/lib/pgadmin
    ports:
      - "8080:80"
    depends_on:
      - postgres
    networks:
      - softuni

volumes:
  my-postgres-data:
  my-data:

networks:
  softuni:
# set to true if network allready exist
    external: true
